name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Java setup
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      # new jar
      - name: Build
        run: chmod +x gradlew && ./gradlew build -x test

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Docker build
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/medical-app .

      - name: Docker push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/medical-app

      # SCRIPT EC2'YE GÖNDERİLİYOR
      - name: Copy script to EC2
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          source: "deploy.sh,docker-compose.yml"
          target: "/home/ec2-user/"

      # SCRIPT EC2'DE ÇALIŞTIRILIYOR
      - name: Run deploy script
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            chmod +x deploy.sh
            ./deploy.sh